/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AiAssistantRouteImport } from './routes/ai-assistant'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ConversationsRouteImport } from './routes/conversations'
import { Route as FollowUpsRouteImport } from './routes/follow-ups'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NoShowsRouteImport } from './routes/no-shows'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as RevenueRouteImport } from './routes/revenue'
import { Route as SuperAdminRouteImport } from './routes/super-admin'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as PatientsIndexRouteImport } from './routes/patients/index'
import { Route as PatientsIdRouteImport } from './routes/patients/$id'
import { Route as SettingsAiRouteImport } from './routes/settings/ai'
import { Route as SettingsClinicRouteImport } from './routes/settings/clinic'
import { Route as SettingsCommunicationRouteImport } from './routes/settings/communication'
import { Route as SettingsIntegrationsRouteImport } from './routes/settings/integrations'
import { Route as SettingsTeamRouteImport } from './routes/settings/team'
import { Route as SuperAdminIndexRouteImport } from './routes/super-admin/index'
import { Route as SuperAdminSettingsRouteImport } from './routes/super-admin/settings'
import { Route as SuperAdminUsersRouteImport } from './routes/super-admin/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAssistantRoute = AiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversationsRoute = ConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const FollowUpsRoute = FollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NoShowsRoute = NoShowsRouteImport.update({
  id: '/no-shows',
  path: '/no-shows',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const RevenueRoute = RevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminRoute = SuperAdminRouteImport.update({
  id: '/super-admin',
  path: '/super-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsIdRoute = PatientsIdRouteImport.update({
  id: '/patients/$id',
  path: '/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAiRoute = SettingsAiRouteImport.update({
  id: '/settings/ai',
  path: '/settings/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsClinicRoute = SettingsClinicRouteImport.update({
  id: '/settings/clinic',
  path: '/settings/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsCommunicationRoute = SettingsCommunicationRouteImport.update({
  id: '/settings/communication',
  path: '/settings/communication',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIntegrationsRoute = SettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsTeamRoute = SettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminIndexRoute = SuperAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminSettingsRoute = SuperAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => SuperAdminRoute,
} as any)
const SuperAdminUsersRoute = SuperAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SuperAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/conversations': typeof ConversationsRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/no-shows': typeof NoShowsRoute
  '/recovery': typeof RecoveryRoute
  '/revenue': typeof RevenueRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/patients/$id': typeof PatientsIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/clinic': typeof SettingsClinicRoute
  '/settings/communication': typeof SettingsCommunicationRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/patients/': typeof PatientsIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/conversations': typeof ConversationsRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/no-shows': typeof NoShowsRoute
  '/recovery': typeof RecoveryRoute
  '/revenue': typeof RevenueRoute
  '/waitlist': typeof WaitlistRoute
  '/patients/$id': typeof PatientsIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/clinic': typeof SettingsClinicRoute
  '/settings/communication': typeof SettingsCommunicationRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/patients': typeof PatientsIndexRoute
  '/super-admin': typeof SuperAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/ai-assistant': typeof AiAssistantRoute
  '/analytics': typeof AnalyticsRoute
  '/conversations': typeof ConversationsRoute
  '/follow-ups': typeof FollowUpsRoute
  '/login': typeof LoginRoute
  '/no-shows': typeof NoShowsRoute
  '/recovery': typeof RecoveryRoute
  '/revenue': typeof RevenueRoute
  '/super-admin': typeof SuperAdminRouteWithChildren
  '/waitlist': typeof WaitlistRoute
  '/patients/$id': typeof PatientsIdRoute
  '/settings/ai': typeof SettingsAiRoute
  '/settings/clinic': typeof SettingsClinicRoute
  '/settings/communication': typeof SettingsCommunicationRoute
  '/settings/integrations': typeof SettingsIntegrationsRoute
  '/settings/team': typeof SettingsTeamRoute
  '/super-admin/settings': typeof SuperAdminSettingsRoute
  '/super-admin/users': typeof SuperAdminUsersRoute
  '/patients/': typeof PatientsIndexRoute
  '/super-admin/': typeof SuperAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/ai-assistant'
    | '/analytics'
    | '/conversations'
    | '/follow-ups'
    | '/login'
    | '/no-shows'
    | '/recovery'
    | '/revenue'
    | '/super-admin'
    | '/waitlist'
    | '/patients/$id'
    | '/settings/ai'
    | '/settings/clinic'
    | '/settings/communication'
    | '/settings/integrations'
    | '/settings/team'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/patients/'
    | '/super-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/ai-assistant'
    | '/analytics'
    | '/conversations'
    | '/follow-ups'
    | '/login'
    | '/no-shows'
    | '/recovery'
    | '/revenue'
    | '/waitlist'
    | '/patients/$id'
    | '/settings/ai'
    | '/settings/clinic'
    | '/settings/communication'
    | '/settings/integrations'
    | '/settings/team'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/patients'
    | '/super-admin'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/ai-assistant'
    | '/analytics'
    | '/conversations'
    | '/follow-ups'
    | '/login'
    | '/no-shows'
    | '/recovery'
    | '/revenue'
    | '/super-admin'
    | '/waitlist'
    | '/patients/$id'
    | '/settings/ai'
    | '/settings/clinic'
    | '/settings/communication'
    | '/settings/integrations'
    | '/settings/team'
    | '/super-admin/settings'
    | '/super-admin/users'
    | '/patients/'
    | '/super-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AiAssistantRoute: typeof AiAssistantRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ConversationsRoute: typeof ConversationsRoute
  FollowUpsRoute: typeof FollowUpsRoute
  LoginRoute: typeof LoginRoute
  NoShowsRoute: typeof NoShowsRoute
  RecoveryRoute: typeof RecoveryRoute
  RevenueRoute: typeof RevenueRoute
  SuperAdminRoute: typeof SuperAdminRouteWithChildren
  WaitlistRoute: typeof WaitlistRoute
  PatientsIdRoute: typeof PatientsIdRoute
  SettingsAiRoute: typeof SettingsAiRoute
  SettingsClinicRoute: typeof SettingsClinicRoute
  SettingsCommunicationRoute: typeof SettingsCommunicationRoute
  SettingsIntegrationsRoute: typeof SettingsIntegrationsRoute
  SettingsTeamRoute: typeof SettingsTeamRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-assistant': {
      id: '/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversations': {
      id: '/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof ConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/follow-ups': {
      id: '/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof FollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/no-shows': {
      id: '/no-shows'
      path: '/no-shows'
      fullPath: '/no-shows'
      preLoaderRoute: typeof NoShowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revenue': {
      id: '/revenue'
      path: '/revenue'
      fullPath: '/revenue'
      preLoaderRoute: typeof RevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin': {
      id: '/super-admin'
      path: '/super-admin'
      fullPath: '/super-admin'
      preLoaderRoute: typeof SuperAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$id': {
      id: '/patients/$id'
      path: '/patients/$id'
      fullPath: '/patients/$id'
      preLoaderRoute: typeof PatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/ai': {
      id: '/settings/ai'
      path: '/settings/ai'
      fullPath: '/settings/ai'
      preLoaderRoute: typeof SettingsAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/clinic': {
      id: '/settings/clinic'
      path: '/settings/clinic'
      fullPath: '/settings/clinic'
      preLoaderRoute: typeof SettingsClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/communication': {
      id: '/settings/communication'
      path: '/settings/communication'
      fullPath: '/settings/communication'
      preLoaderRoute: typeof SettingsCommunicationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/integrations': {
      id: '/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof SettingsIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/team': {
      id: '/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof SettingsTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/': {
      id: '/super-admin/'
      path: '/'
      fullPath: '/super-admin/'
      preLoaderRoute: typeof SuperAdminIndexRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/settings': {
      id: '/super-admin/settings'
      path: '/settings'
      fullPath: '/super-admin/settings'
      preLoaderRoute: typeof SuperAdminSettingsRouteImport
      parentRoute: typeof SuperAdminRoute
    }
    '/super-admin/users': {
      id: '/super-admin/users'
      path: '/users'
      fullPath: '/super-admin/users'
      preLoaderRoute: typeof SuperAdminUsersRouteImport
      parentRoute: typeof SuperAdminRoute
    }
  }
}

interface SuperAdminRouteChildren {
  SuperAdminSettingsRoute: typeof SuperAdminSettingsRoute
  SuperAdminUsersRoute: typeof SuperAdminUsersRoute
  SuperAdminIndexRoute: typeof SuperAdminIndexRoute
}

const SuperAdminRouteChildren: SuperAdminRouteChildren = {
  SuperAdminSettingsRoute: SuperAdminSettingsRoute,
  SuperAdminUsersRoute: SuperAdminUsersRoute,
  SuperAdminIndexRoute: SuperAdminIndexRoute,
}

const SuperAdminRouteWithChildren = SuperAdminRoute._addFileChildren(
  SuperAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AiAssistantRoute: AiAssistantRoute,
  AnalyticsRoute: AnalyticsRoute,
  ConversationsRoute: ConversationsRoute,
  FollowUpsRoute: FollowUpsRoute,
  LoginRoute: LoginRoute,
  NoShowsRoute: NoShowsRoute,
  RecoveryRoute: RecoveryRoute,
  RevenueRoute: RevenueRoute,
  SuperAdminRoute: SuperAdminRouteWithChildren,
  WaitlistRoute: WaitlistRoute,
  PatientsIdRoute: PatientsIdRoute,
  SettingsAiRoute: SettingsAiRoute,
  SettingsClinicRoute: SettingsClinicRoute,
  SettingsCommunicationRoute: SettingsCommunicationRoute,
  SettingsIntegrationsRoute: SettingsIntegrationsRoute,
  SettingsTeamRoute: SettingsTeamRoute,
  PatientsIndexRoute: PatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
